name: Bloodmoon
version: '${project.version}'
main: net.bingecraft.bloodmoon.Plugin
api-version: 1.19
commands:
  bloodmoon:
    description: set difficulty to hard
    usage: /<command>
    permission: bloodmoon